## 1. Say "Hello, World!" With Python

In [1]:
str = "Hello, World!"
print(str)

Hello, World!


## 2. Python If-Else

In [2]:
n = int(input().strip())
if n%2==1:
    print("Weird")
elif n%2==0 and 2<=n<=5:
    print("Not Weird")
elif n%2==0 and 6<=n<=20:
    print("Weird")
else:
    print("Not Weird")

Weird


## 3. Arithmetic Operators

In [3]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a+b)
    print(a-b)
    print(a*b)

ValueError: invalid literal for int() with base 10: 'BANANA FRITA 10'

## 4. Python: Division

In [ ]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a//b)
    print(a/b)

3
5
0
0.6


## 5. Loops

In [ ]:
if __name__ == '__main__':
    n = int(input())
    l = range(0,n)
    for i in l:
        print(i**2)

5
0
1
4
9
16


## 6. Write a function

In [ ]:
def is_leap(year):
    leap = False
    if(year%4==0):  
        if(year%100==0):    
            if(year%400==0):
                leap = True
            else:
                leap = False
        else:
            leap = True
    else:
        leap = False           
    return leap              
year = int(input())
print(is_leap(year))

1992
True


## 7. Print Function

In [ ]:
if __name__ == '__main__':
    n = int(input())
    l = range(1,n+1)
    for i in l:
        print(i,end='')

5
12345

## 8. List Comprehensions

In [ ]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())

l=[[i,j,k] for i in range(0,x+1) for j in range(0,y+1) for k in range(0,z+1) if i+j+k !=n ]
print(l)


1
1
2
3
[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 2]]


## 9. Find the Runner-Up Score!

In [ ]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    l = set(arr)
    l_s = sorted(list(l))
    print(l_s [-2])

5
2 3 6 6 5
5


## 10. Nested Lists

In [ ]:
l = []
s = []

if __name__ == '__main__':
    for _ in range(int(input())):
        name = input()
        score = float(input())
        l = l + [[name,score]]
        s = s + [score]
    m = list(sorted(set(s)))
    u = m[1]
    n = sorted(l)
    for i,j in n:
        if u==j:
            print(i)
    

4
Prashant
32
Pallavi
36
Dheeraj
39
Shivam
40
[32.0, 36.0, 39.0, 40.0]
36.0
Pallavi


## 11. Finding the percentage

In [ ]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
l = (student_marks[query_name])
a = len(l)
p = sum(l)/a
print ("%.2f"%p) 

2
a 1 2 3
b 2 3 4
a
2.00
[2.0, 3.0, 4.0]


## 12. Lists

In [ ]:
if __name__ == '__main__':
    N = int(input())
    l =[]
    for i in range(0,N):
        r=input().split()
        if r[0] == 'sort':
            l.sort()
        elif r[0] == 'print':
            print(l)
        elif r[0] == 'pop':
            l.pop()
        elif r[0] == 'insert':
            l.insert(int(r[1]),int(r[2]))
        elif r[0] =='append':
            l.append(int(r[1]))
        elif r[0] =='remove':
            l.remove(int(r[1]))
        elif r[0] =='reverse':
            l.reverse() 

2
insert 0 1 2
remove 1


## 13. Tuples

In [ ]:
n = int(input())
integer_list = map(int, input().split())
t=tuple(integer_list)
h=hash(t)
print(h)

# Has to run in pyp3 to have the correct ans. Saw it in the discussions section.

2
1 2
-3550055125485641917


## 14. sWAP cASE

In [ ]:
def swap_case(s):
    l = ''
    for i in s:
        if i.isupper() == False:
            l = l + i.upper()
        else:
            l = l + i.lower()
    return l

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

amarillo
AMARILLO


## 15. String Split and Join

In [ ]:
def split_and_join(line):
    l = line.split()
    l = '-'.join(l)
    return l

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

this is a string
['this', 'is', 'a', 'string']
this-is-a-string


## 16. What's Your Name?

In [ ]:
def print_full_name(first, last):
    print('Hello '+ first +' '+ last + '! You just delved into python.')

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

Ross
Taylor
Hello Ross Taylor! You just delved into python.


## 17. Mutations

In [ ]:
def mutate_string(string, position, character):
    l= list(string)
    l[position] = character
    s =''.join(l)
    
    return s

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

abracadabra
5 k
abrackdabra


## 18. Find a string

In [ ]:
def count_substring(string, sub_string):
    a = len(string)
    b = len(sub_string)
    count=0
    for i in range(0, a-b+1):
        if string[i] == sub_string[0]:
            coin=1
            for j in range(0, b):
                if string[i+j] != sub_string[j]:
                    coin = 0
                    break
            if coin==1:
                count = count + 1  
    return count

if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)
#I relied on information found about for in another for to compare the sub_string with the string when the first letter matches.

ABCDCDC
CDC
2


## 19. String Validators

In [ ]:
if __name__ == '__main__':
    s = input()
    #check alph number
    n = (l.isalnum() for l in s)
    print(any(n))
    #check alph
    a = (l.isalpha() for l in s)
    print(any(a))
    #check digits
    d = (l.isdigit() for l in s)
    print(any(d))
    #check lower_c
    lo = (l.islower() for l in s)
    print(any(lo))
    #check upper_c
    u = (l.isupper() for l in s)
    print(any(u))

qA2
True
True
True
True
True


## 20. Text Alignment

In [ ]:
#Replace all ______ with rjust, ljust or center. 

thickness = int(input()) #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

#Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))    

#Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))    

#Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))

7
      H      
     HHH     
    HHHHH    
   HHHHHHH   
  HHHHHHHHH  
 HHHHHHHHHHH 
HHHHHHHHHHHHH
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH    
   HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH    
   HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH    
   HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH    
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH                  
   HHHHHHH                     HHHHHHH      

## 21. Text Wrap

In [ ]:
import textwrap

def wrap(string, max_width):
    l = len(string)
    for i in range(0,l+1,max_width):
        ans = string[i:i+max_width]
        if max_width==len(ans):
            print(ans)
        else:
            return(ans)
if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)
#I realied on informtation found on internet on how to create an if to print an answer in a function insted of use the "return" because the return option only showed the last 'YZ' letters.

ABCDEFGHIJKLMNOPQRSTUVWXYZ
4
ABCD
EFGH
IJKL
MNOP
QRST
UVWX
YZ


## 22. Designer Door Mat

In [ ]:
l = map(int,input().split())
N, M = l
for i in range(1,N,2):
    f = ('.|.'*i).center(M,'-')
    print(f)
print('WELCOME'.center(M,'-'))
for i in range(N-2,0,-2):
    b = ('.|.'*i).center(M,'-')
    print(b)


9 27
------------.|.------------
---------.|..|..|.---------
------.|..|..|..|..|.------
---.|..|..|..|..|..|..|.---
----------WELCOME----------
---.|..|..|..|..|..|..|.---
------.|..|..|..|..|.------
---------.|..|..|.---------
------------.|.------------


## 23. String Formatting

In [ ]:
def print_formatted(number):
    l = len(bin(number)[2:])
    for i in range(1, number+1):
        d = str(i)
        o = str(oct(i))[2:]
        h = str(hex(i))[2:]
        h = h.upper()
        b = str(bin(i))[2:]
        print(d.rjust(l,' '),o.rjust(l,' '),h.rjust(l,' '),b.rjust(l,' '))
        
if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

17
    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001


## 24. Alphabet Rangoli

In [ ]:
def print_rangoli(size):
    l = size
    a = ''
    r = ''
    m = []
    
    for i in range(l):
        a = a + chr(97+i)
    
    for i in a[::-1]:
        r=r + ('-'+i)
        b=r+r[(len(r)-2)::-1]
        m.append(b)
        m[-1]=m[-1].strip('-')
        
    for i in m:
        ans = i.center(len(m[-1]),'-')
        print(ans)
        
    for i in m[-2::-1]:
        ans_b = i.center(len(m[-1]),'-')
        print(ans_b)
    
if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)
#I relied on information found on internet on how to use chr (str to letters) and the correct use of slice notation

5
--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


## 25. Capitalize!

In [ ]:
import math
import os
import random
import re
import sys

def solve(s):
    for i in s.split():
        s = s.replace(i,i.capitalize())
    print(s)

if __name__ == '__main__':

    #fptr = open(os.environ['OUTPUT_PATH'], 'w')
    
    s = input()

    result = solve(s)

    #fptr.write(result + '\n')

    #fptr.close()
# I relied on information found on internet about capitalize and replace a value

maria pena
Maria Pena


## 26. The Minion Game

In [ ]:
def minion_game(string):
    v='AEIOU'
    s=0 #consonants
    k=0 #vowels
    
    for i in range(len(string)):
        if string[i] not in v:
            #s = s + len(string[i:])
            s = s + len(string)-i
        else:
            #k = k + len(string[i:])
            k = k + len(string)-i
    
    if(k>s):
        print('Kevin '+ str(k))
    elif(s>k):
        print('Stuart '+ str(s))
    else:
        print('Draw')

if __name__ == '__main__':
    s = input()
    minion_game(s)
#Found information on internet about how to count the len of the string in a for in multiple ways

BANANA
Stuart 12


## 27. Merge the Tools!

In [ ]:
def merge_the_tools(string, k):
    l=[]
    le=(len(string))//k
    v=0
    for i in range(le):
        l.append(string[v:(v+k)])
        v= v+k
        
    for j in l:
        a = list(j)
        d = dict.fromkeys(a)
        l2 = list(d)
        ans = ''.join(l2)
        print(ans)
        
if __name__ == '__main__':
    string, k = input(), int(input())
    merge_the_tools(string, k)

AABCAAADA
3
AB
CA
AD


## 28. Introduction to Sets

In [ ]:
def average(array):
    s = set(array)
    return sum(s)/len(s)

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

10
161 182 161 154 176 170 167 171 170 174
169.375


## 29. No Idea!

In [ ]:
h=0
e=input().split()
n,m=e
array=list(input().split(' '))
a=set(input().split(' '))
b=set(input().split(' '))

print(array)
print(a)
print(b)

for i in array:
    if i in a:
        h= h+1
    elif i in b:
        h= h-1
print(h)        

5 5
999999991 999999992 999999993 999999994 999999999
999999991 999999993 999999995 999999999 999999997
999999990 999999992 999999996 999999998 999999994
['999999991', '999999992', '999999993', '999999994', '999999999']
{'999999999', '999999997', '999999993', '999999995', '999999991'}
{'999999990', '999999998', '999999994', '999999996', '999999992'}
1


## 30. Symmetric Difference

In [ ]:
m = int(input())
m_m= set(map(int,input().split(' ')))
n = int(input())
n_n= set(map(int,input().split(' ')))

d1=m_m.difference(n_n)
d2=n_n.difference(m_m)
ans= d1.union(d2)

l=sorted(list(ans))
for i in l:
    print(i)

4
2 4 5 9
4
2 4 11 12
5
9
11
12


## 31. Set .add()

In [ ]:
n = int(input())
c= set()
for i in range (0,n):
    c.add(input())
print(len(c))

7
UK
China
USA
France
New Zeland
UK
France
5


## 32. Set .discard(), .remove() & .pop()

In [ ]:
n=int(input())
s=set(map(int,input().split(' ')))
N=int(input())
for i in range (0,N):
    o=input().split()
    if o[0]=='pop':
        s.pop()
    elif o[0]=='remove':
        e = int(o[1])
        s.remove(e)
    else:
        e = int(o[1])
        s.discard(e)
ans=sum(list(s))
print(ans)

9
1 2 3 4 5 6 7 8 9
10
pop
remove 9
discard 9
discard 8
remove 7
pop
discard 6
remove 5
pop
discard 5
4


## 33. Set .union() Operation

In [ ]:
n=int(input())
n_s=set(map(int,input().split(' ')))
b=int(input())
b_s=set(map(int,input().split(' ')))

ans = n_s.union(b_s)
ans_2= list(ans)
print(len(ans_2))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
13


## 34. Set .intersection() Operation

In [ ]:
n=int(input())
n_s=set(map(int,input().split(' ')))
b=int(input())
b_s=set(map(int,input().split(' ')))

ans = n_s.intersection(b_s)
ans_2=list(ans)
print(len(ans_2))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


## 35. Set .difference() Operation

In [ ]:
n=int(input())
n_s=set(map(int,input().split(' ')))
b=int(input())
b_s=set(map(int,input().split(' ')))

ans = n_s.difference(b_s)
ans_2=list(ans)
print(len(ans_2))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


## 36. Set .symmetric_difference() Operation

In [ ]:
n=int(input())
n_s=set(map(int,input().split(' ')))
b=int(input())
b_s=set(map(int,input().split(' ')))

ans = n_s.symmetric_difference(b_s)
ans_2=list(ans)
print(len(ans_2))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
8


## 37. Set Mutations

In [ ]:
a=int(input())
a_s=set(map(int,input().split(' ')))
n=int(input())
for i in range(0,n):
    o,o_o=input().split()
    e=set(map(int,input().split(' ')))
    if o=='update':
        a_s.update(e)
    elif o=='intersection_update':
        a_s.intersection_update(e)
    elif o=='symmetric_difference_update':
        a_s.symmetric_difference_update(e)
    elif o=='difference_update':
        a_s.difference_update(e)
ans = sum(a_s)
print(ans)

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
38


## 38. The Captain's Room

In [ ]:
k = int(input())
k_s= list(map(int, input().split(' ')))
ans = {}
for i in k_s:
    if i in ans:
          ans[i]= ans[i]+1
    else:
          ans[i]=1
for i in ans:
    if ans[i] == 1:
          print(ans)
          break
#Found information on internet on how to count using dictionaries

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
8


## 39. Check Subset

In [ ]:
T = int(input())
for i in range(0,T):
    A = int(input())
    a_a = set(map(int,input().split(' ')))
    
    B = int(input())
    b_b = set(map(int,input().split(' ')))
    
    ans = a_a.difference(b_b)
    if len(ans) ==0:
        print("True")
    else:
        print("False")

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
0
True
1
2
5
3 6 5 4 1
1
False
7
1 2 3 5 6 8 9
3
9 8 2
4
False


## 40. Check Strict Superset

In [ ]:
A = set(map(int,input().split(' ')))
n = int(input())
sol=0
false=0
for i in range(0,n):
    s = set(map(int,input().split(' ')))
    if A.issuperset(s):
        sol = sol+1
    else:
        false= false+1
if false>0:
    print("False")
else:
    print("True")

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


## 41. collections.Counter()

In [ ]:
from collections import Counter

X = int(input())
l = list(map(int, input().split(' ')))
c = Counter(l)
N = int(input())
ans=0
for i in range(0,N):
    s,x = map(int,input().split())
    if s in c and c[s]>0:
        ans = ans + x
        c[s] = c[s]-1
print(ans)

10
2 3 4 5 6 8 7 6 5 18
6
6 55
6 45
6 55
4 40
18 60
10 50
255


## 42. DefaultDict Tutorial

In [ ]:
from collections import defaultdict
n, m = list(map(int,input().split(' ')))
d = defaultdict(list)
for i in range (1,n+1):
    a = input()
    d[a].append(i)
for j in range (0,m):
    b = input()
    if b in d:
        ans = d[b]
        print(*ans)
    else:
        print("-1")
#Found information on internet on how to append in a defaultdict and how to decompress a list 

5 2
a
a
b
a
b
a
1 2 4
b
3 5


## 43. Collections.namedtuple()

In [ ]:
import collections
N=int(input())
summ=[]
r = 0

for i in range (0,N+1):
    if i ==0:
        title = input()
        tit_2=collections.namedtuple('Student',title)
    else:
        a,b,c,d=list(input().split())
        ans=tit_2(a,b,c,d)
        summ.append(ans)
for i in summ:
    l = int(i.MARKS)
    r = r + l
    res = r/N
print("%.2f"%res)

5
MARKS      CLASS      NAME       ID        
92         2          Calum      1         
82         5          Scott      2         
94         2          Jason      3         
55         8          Glenn      4         
82         2          Fergus     5
81.00


## 44. Collections.OrderedDict()

In [10]:
import collections
N = int(input())
ans = collections.OrderedDict()

for i in range (0,N):
    l = input().split(' ')
    precio = int(l[-1])
    nombre= " ".join(l[:-1])
   
    if nombre in ans:
        ans[nombre] += precio
    else:
        ans[nombre] = precio

for llave,valor in ans.items():
    print(llave,valor)

r 1
a 2


## 45. Word Order

In [14]:
n= int(input())
ans = collections.OrderedDict()

for i in range(0,n):
    palabra = input()
    
    if palabra in ans:
        ans[palabra] += 1
    else:
        ans[palabra] = 1

print(len(ans))

for llave,valor in ans.items():
    print(valor,end=" ")


3
2 1 1 

## 46. Collections.deque()

In [23]:
N = int(input())
ans = collections.deque()

for i in range(0,N):
    accion = input().split(' ')
    if accion[0] == 'append':
        ans.append(accion[1])
    elif accion[0] == 'pop':
        ans.pop()
    elif accion[0] == 'popleft':
        ans.popleft()
    elif accion[0] == 'appendleft':
        ans.appendleft(accion[1])

for valor in ans:
    print(valor, end=" ")   


1 2 

## 47. Company Logo

In [2]:
import collections

s = list(input())
sor = sorted(s)
top_frecuentes = collections.Counter(sor)

for letter, count in top_frecuentes.most_common(3):
    print(letter,count)


b 3
a 2
c 2


## 48. Piling Up!

In [8]:
T = int(input())
ans = []

for i in range (0,T):
    n = int(input())
    l = list(map(int,input().split(' ')))
    
    for i in range(0,n-1):
        if l[0] >= l[len(l)-1]:
            var = l[0]
            l.pop(0)
        elif l[0] < l[len(l)-1]:
            var = l[len(l)-1]
            l.pop(len(l)-1)
        else:
            continue

        if len(l)==1:
            ans.append('Yes')
        
        if((l[0]>var) or (l[len(l)-1]>var)):
            ans.append('No')

            break

print("\n".join(ans))


Yes
No


## 49. Calendar Module

In [22]:
import calendar
import datetime
list = []
mes,dia,ano = map(int, input().split(' '))
fecha = datetime.date(ano, mes, dia)
nombre_dia = fecha.weekday()

ans = calendar.day_name[nombre_dia]
print(ans.upper())


WEDNESDAY


## 50. Time Delta

In [28]:
import math
import os
import random
import re
import sys
from datetime import datetime

# Complete the time_delta function below.
def time_delta(t1, t2):
    primera_fecha = datetime.strptime(t1, '%a %d %b %Y %H:%M:%S %z')
    segunda_fecha = datetime.strptime(t2, '%a %d %b %Y %H:%M:%S %z')

    ans = abs(primera_fecha-segunda_fecha)
    ans = ans.total_seconds()
    print(int(ans))


if __name__ == '__main__':
    #fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)


        #fptr.write(delta + '\n')

   #fptr.close()
#Found information on internet on how tu use strptime and its date formats to convert a date in a number

25200
88200


## 51. Exceptions

In [32]:
T = int(input())

for i in range(0,T):
    try:
        a,b = map(int, input().split(' '))
        print(a//b)
    except Exception as e:
        print("Error Code:",e)


Error code: integer division or modulo by zero
Error code: invalid literal for int() with base 10: '$'
3


## 52. Zipped!

In [38]:
N, X = input().split(' ')
X = int(X)
notas =[]
for i in range (0,X):
    list = map(float,input().split(' '))
    notas.append(list)

for nota in zip(*notas):
    X = sum(nota)/len(nota)
    print(X)
# Found information on internet on how (*var) works

90.0
91.0
82.0
90.0
85.5


## 53. Athlete Sort

In [2]:
#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    k = int(input())

    arr.sort(key= lambda student: student[k])

    for grades in arr:
        print(*grades)

#Found information on internet on how to use lambda in a sort function.


[[10, 2, 5], [7, 1, 0], [9, 9, 9], [1, 23, 12], [6, 5, 9]]
7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


## 54. ginortS

In [17]:
S = input()

mayuscula = []
minus = []
impar = []
par = []

for letras in S:
    if letras.isalpha():
        if letras.isupper():
            mayuscula.append(letras)
        else:
            minus.append(letras)
    else:
        if int(letras)%2 ==0:
            par.append(letras)
        else:
            impar.append(letras)

minus_s = sorted(minus)
mayus_s = sorted(mayuscula)
impar_s = sorted(impar)
par_s = sorted(par)

ans = ''.join(minus_s)+''.join(mayus_s)+''.join(impar_s)+''.join(par_s)

print(ans)


ginortS1324


## 55. Map and Lambda Function

In [21]:
cube = lambda x: x**3

def fibonacci(n):
    num_1 = 0
    num_2 = 1
    num_3 = 0
    ans = []
    while n>0:
        ans.append(num_1)
        num_3 = num_1 + num_2
        num_1 = num_2
        num_2 = num_3
        n= n-1
    return ans

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

#Found information on internet on how to create a code using the fibonnaci numbers

[0, 1, 1, 8, 27]


## 56. XML 1 - Find the Score

In [22]:
import sys
import xml.etree.ElementTree as etree

def get_attr_number(node):
    cont =0
    for attr in node:
        cont = cont + get_attr_number(attr)
    ans = cont + len(node.attrib)
    return(ans)
    
if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))

#Found information on internet on XML. I didn't know how to work with one.

ParseError: no element found: line 1, column 0 (<string>)

## 57. XML2 - Find the Maximum Depth

In [23]:
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    if level==maxdepth:
        maxdepth = maxdepth + 1
    for i in elem:
        depth(i, level + 1)

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)
#Found information on internet about XML depth and how to use pyhton to calculate it.

1


## 58. Standardize Mobile Number Using Decorators

In [31]:
def wrapper(f):
    def fun(l):
        ans =[]
        for number in l:
            a = []
            a = number[::-1][0:10][::-1]
            a = ' '.join(["+91"]+[a[0:5], a[5:]])
            ans.append(a)
        f(ans)
    return fun

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 


+91 78954 62130
+91 91959 69878
+91 98756 41230


## 59. Decorators 2 - Name Directory

In [8]:
import operator

def person_lister(f):
    def inner(people):
        a = []
        a = sorted(people, key = lambda person: int(person[2]))
        return (f(persona) for persona in a)
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


 ## 60. Arrays

In [5]:
import numpy

def arrays(arr):
    ans = numpy.array(arr[::-1],float)
    return ans

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

[-10.  -8.   4.   3.   2.   1.]
None


## 61. Shape and Reshape

In [10]:
import numpy
l = input().split(' ')
l_ans = numpy.array(l,int)
print (numpy.reshape(l_ans,(3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 62. Transpose and Flatten

In [15]:
import numpy
N, M = map(int,input().split(' '))
l = []
for i in range (0,N):
    N_2 = list(input().split(' '))
    l.append(N_2)
ans = numpy.array(l, int)
trans = numpy.transpose(ans)
flatten = ans.flatten()
print(trans)
print(flatten)

[[1 3]
 [2 4]]
[1 2 3 4]


## 63. Concatenate

In [18]:
import numpy
N, M, P = map(int,input().split(' '))
l_1 = []
l_2 = []
for i in range (0,N):
    N_2 = list(input().split(' '))
    l_1.append(N_2)
for i in range (0,M):
    M_2 = list(input().split(' '))
    l_2.append(M_2)
ans_n = numpy.array(l_1, int)
ans_m = numpy.array(l_2, int)
ans = numpy.concatenate((ans_n,ans_m), axis = 0)
print(ans)


[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]]


## 64. Zeros and Ones


In [21]:
import numpy
l = map(int,input().split(' '))
l = tuple(l)
l_1 = numpy.zeros(l,int)
l_2 = numpy.ones(l,int)
print(l_1)
print(l_2)

(3, 3, 3)
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## 65. Eye and Identity

In [27]:
import numpy
numpy.set_printoptions(legacy='1.13')
l = map(int,input().split(' '))
print(numpy.eye(*l))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## 66. Array Mathematics

In [30]:
import numpy
N, M = map(int,input().split(' '))
l_1 =[]
l_2 = []
for i in range (0,N):
    ans_1 = list(map(int,input().split(' ')))
    l_1.append(ans_1)
for i in range (0,N):
    ans_2 = list(map(int,input().split(' ')))
    l_2.append(ans_2)

nl1 = numpy.array(l_1)  
nl2 = numpy.array(l_2)

print(nl1 + nl2)
print(nl1 - nl2)
print(nl1 * nl2)
print(nl1 // nl2)
print(nl1 % nl2)
print(nl1 ** nl2)

[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## 67. Floor, Ceil and Rint

In [31]:
import numpy
numpy.set_printoptions(legacy='1.13')

A = list(map(float, input().split(' ')))
ans = numpy.array(A,float)

print(numpy.floor(ans))
print(numpy.ceil(ans))
print(numpy.rint(ans))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## 68. Sum and Prod

In [38]:
import numpy
N, M = map(int,input().split(' '))
l = []

for i in range (0,N):
    ans = list(map(int,input().split(' ')))
    l.append(ans)
n_ans = numpy.array(l)
n_sum = numpy.sum(n_ans, axis = 0)
n_prod = numpy.prod(n_sum, axis = 0)
print(n_prod)

24


## 69. Min and Max

In [41]:
import numpy
N, M = map(int,input().split(' '))
l = []

for i in range (0,N):
    ans = list(map(int,input().split(' ')))
    l.append(ans)
n_ans = numpy.array(l)
n_min = numpy.min(n_ans, axis = 1)
n_max = numpy.max(n_min)
print(n_max)

3


## 70. Mean, Var, and Std

In [44]:
import numpy
N, M = map(int,input().split(' '))
l = []

for i in range (0,N):
    ans = list(map(int,input().split(' ')))
    l.append(ans)
n_ans = numpy.array(l)
n_mean = numpy.mean(n_ans, axis = 1)
n_var = numpy.var(n_ans, axis = 0)
n_std = round(numpy.std(n_ans),11)
print(n_mean)
print(n_var)
print(n_std)

[ 1.5  3.5]
[ 1.  1.]
1.11803398875


## 71. Dot and Cross

In [48]:
import numpy

N = int(input())
l_a = []
l_b = []

for i in range (0,N):
    A = list(map(int,input().split(' ')))
    l_a.append(A)

for i in range (0,N):
    B = list(map(int,input().split(' ')))
    l_b.append(B)

ans_a = numpy.array(l_a)
ans_b = numpy.array(l_b)

print(numpy.dot(ans_a,ans_b))


[[19 22]
 [43 50]]


## 72. Inner and Outer

In [50]:
import numpy

A = list(map(int,input().split(' ')))
B = list(map(int,input().split(' ')))

ans_a = numpy.array(A)
ans_b = numpy.array(B)

print(numpy.inner(ans_a, ans_b))
print(numpy.outer(ans_a, ans_b))

3
[[0 0]
 [2 3]]


## 73. Polynomials

In [51]:
import numpy

P = list(map(float,input().split(' ')))
x = int(input())

n_p = numpy.array(P)

print(numpy.polyval(n_p,x))


3.0


## 74. Linear Algebra

In [66]:
import numpy 

N = int(input())
l_a = []

for i in range(0,N):
    A = list(map(float,input().split(' ')))
    l_a.append(A)

ans_a = numpy.array(l_a,float)
print(round(numpy.linalg.det(ans_a),2))

6.0


## 75. Detect Floating Point Number

In [2]:
import re

pattern = '^(-|\+)?\d*\.\d+$'

prog = re.compile(pattern)

test = lambda n: bool(prog.match(n))

t = int(input().strip())

for x in range(t):
    n = input().strip()
    print(test(n))


False
True
True
False


## 76. Re.split()

In [3]:
regex_pattern = r"[\.,]"	# Do not delete 'r'.

import re
print("\n".join(re.split(regex_pattern, input())))

100
000
000
000


## 77. Group(), Groups() & Groupdict()

In [4]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re

pattern = '.*?(?P<g1>[0-9a-zA-Z])(?P=g1).*'

prog = re.compile(pattern)

def test(n):
    gs = prog.match(n)
    return '-1' if not gs else gs.group('g1')

S = input().strip()

print(test(S))

1


## 78. Re.findall() & Re.finditer()

In [8]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re

# Vowels are defined as: AEIOU and aeiou. 
vowels = '[AEIOUaeiou]'
# Consonants are defined as: QWRTYPSDFGHJKLZXCVBNM and qwrtypsdfghjklzxcvbnm.
consonants = '[QWRTYPSDFGHJKLZXCVBNMqwrtypsdfghjklzxcvbnm]'

pattern = '(?<={consonants}){vowels}{{2,}}(?={consonants})' \
    .format(consonants=consonants, vowels=vowels)

prog = re.compile(pattern)

def test(n):
    rs = prog.findall(n)
    
    if not rs: 
        print('-1')
    else:
        for f in prog.findall(n):
            print(f)

S = input().strip()
test(S)

AA


## 79. Re.start() & Re.end()

In [11]:
import re

def test(s, k):
    
    pattern = '{head}(?={tail})' \
        .format(head=k[0], tail=k[1:])   
    
    ms = list(re.finditer(pattern, s))
    
    if not ms:
        print('(-1, -1)')
    else:
        for m in ms:
            print(f'({m.start()}, {m.start() + len(k) - 1})')


s = input().strip()
k = input().strip()
test(s, k)

a(?=a)
(0, 1)
(1, 2)
(4, 5)


## 80. Regex Substitution

In [4]:
# Enter your code here. Read input from STDIN. Print output to STDOUT

import re

conversion = lambda m: ' and' if m.group(0) == ' &&' else ' or'

prog = re.compile('(( \|\|)|( &&))(?= )')

sub = lambda l: prog.sub(conversion, l)

t = int(input().strip())

for x in range(t):
    line = input()
    print(sub(line))

elif a*b > 10 or a/b < 1:


## 81. Validating Roman Numerals

In [10]:
regex_pattern = r"^M{0,3}(CM|CD|D?C{0,3})?(XC|XL|L?X{0,3})?(IX|IV|V?I{0,3})?$"	# Do not delete 'r'.

import re

print(str(bool(re.match(regex_pattern, input()))))

#Found information on internet on regex pattern to validate roman numbers. Source: https://dev.to/alexdjulin/a-python-regex-to-validate-roman-numerals-2g99


False


## 82. Validating phone numbers

In [6]:
import re

prog = re.compile('^[789]\d{9}$')

valid_phone = lambda line: bool(prog.match(line))

n = int(input().strip())
lines = [input().strip() for x in range(n)]

for line in lines:
    print('YES' if valid_phone(line) else 'NO')

YES
NO
NO


## 83. Validating and Parsing Email Addresses

In [9]:
import re
import email.utils

english_alphabetical = '[AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz]'

username_chars = '{english_alphabetical}[\w\-_\.]+' \
    .format(english_alphabetical=english_alphabetical)

pattern = '^{username_chars}@{domain}+\.{extension}{{1,3}}$' \
    .format(
        username_chars=username_chars,
        domain=english_alphabetical,
        extension=english_alphabetical,)

prog = re.compile(pattern)

def valid_email(line):
    user, mail = email.utils.parseaddr(line)
    return bool(prog.match(mail))

n = int(input().strip())
lines = [input().strip() for x in range(n)]

for valid in filter(valid_email, lines):
    print(valid)


DEXTER <dexter@hotmail.com>


## 84. Hex Color Code

In [20]:
import re

hex_value_re = re.compile('#(?:[\dA-Fa-f]{3}){1,2}')

def get_value_if_present(line): 
    m = re.match('^[^:]+:(?P<value>.*);.*$', line)
    return m.group('value') if m else None

hex_colors = lambda value: re \
    .findall('#(?:[\dA-Fa-f]{3}){1,2}', value)

def hex_colors_from_line(line):
    value = get_value_if_present(line)
    return [] if not value else hex_colors(value)

n = int(input().strip())
lines = [input().strip() for x in range(n)]

for line in lines:
    for hex_color in hex_colors_from_line(line):
        print(hex_color)

#f9f9f9
#fff


## 85. HTML Parser - Part 1

In [24]:
from html.parser import HTMLParser

# create a subclass and override the handler methods
class MyHTMLParser(HTMLParser):
    
    def __print_attrs(self, attrs):
        for name, value in attrs:
            print(f'-> {name} > {value}')
    
    def handle_starttag(self, tag, attrs):
        print(f'Start : {tag}')
        self.__print_attrs(attrs)
        
    def handle_endtag(self, tag):
        print(f'End   : {tag}')
        
    def handle_startendtag(self, tag, attrs):
        print(f'Empty : {tag}')
        self.__print_attrs(attrs)
        

n = int(input().strip())
lines = [input().strip() for x in range(n)]
html = ''.join(lines)

  
parser = MyHTMLParser()
parser.feed(html)
parser.close() 

Start : html
Start : head
Start : title
End   : title
End   : head


## 86. HTML Parser - Part 2

In [26]:
from html.parser import HTMLParser

# create a subclass and override the handler methods
class MyHTMLParser(HTMLParser):
    
    def handle_comment(self, data):
        print('>>> Single-line Comment' if '\n' not in data else '>>> Multi-line Comment')
        print(data)
    
    def handle_data(self, data):
        
        if data == '\n':
            return
        
        print('>>> Data')
        print(data)
        
html = ""       
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'

parser = MyHTMLParser()
parser.feed(html)
parser.close() 

<!--[if IE 9]>IE9-specific content
<![endif]-->
<div> Welcome to HackerRank</div>
<!--[if IE 9]>IE9-specific content<![endif]-->

>>> Multi-line Comment
[if IE 9]>IE9-specific content
<![endif]
>>> Data
 Welcome to HackerRank
>>> Single-line Comment
[if IE 9]>IE9-specific content<![endif]


## 87. Detect HTML Tags, Attributes and Attribute Values

In [27]:
from html.parser import HTMLParser

# create a subclass and override the handler methods
class MyHTMLParser(HTMLParser):
    
    def handle_starttag(self, tag, attrs):
        print(tag)
        
        for name, value in attrs:
            print(f'-> {name} > {value}')

        
n = int(input().strip())
lines = [input().strip() for x in range(n)]
html = ''.join(lines)
#print(html)
   
parser = MyHTMLParser()
parser.feed(html)
parser.close()

<head><title>HTML</title></head><object type="application/x-flash"data="your-file.swf"width="0" height="0"><!-- <param name="movie" value="your-file.swf" /> --><param name="quality" value="high"/></object>
head
title
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
param
-> name > quality
-> value > high


## 88. Validating UID

In [28]:
import re

def valid_uid(uid):
    
    # It should only contain alphanumeric characters (A - z, A - Z & 0 - 9).
    # There must be exactly 10 characters in a valid UID.
    if not re.match('^[a-zA-Z0-9]{10}$', uid):
        return False

    # It must contain at least 2 uppercase English alphabet characters.
    if len(re.findall('[A-Z]', uid)) < 2:
        return False
    
    # It must contain at least 3 digits (0 - 9).
    if len(re.findall('(\d)', uid)) < 3:
        return False
    
    # No character should repeat.
    if re.match('^.*(?P<char>.).*?(?P=char).*$', uid):
        return False

    # Else
    return True

n = int(input().strip())
lines = [input().strip() for x in range(n)]

for line in lines:
    print('Valid' if valid_uid(line) else 'Invalid')

Invalid
Valid


## 89. Validating Credit Card Numbers

In [31]:
import re

def valid_cc_number(uid):
    
    # It must start with a 4, 5 or 6. 
    # It must contain exactly 16 digits. 
    # It must only consist of digits (0-9). 
    # It may have digits in groups of 4, separated by one hyphen "-". 
    # It must NOT use any other separator like ' ' , '_', etc. 
    if not re.match('^[4-6]\d{3}((\d{12})|(-\d{4}-\d{4}-\d{4}))$', uid):
        return False
    
    # It must NOT have 4 or more consecutive repeated digits.
    if re.match('^.*(?P<char>.)-?(?P=char)-?(?P=char)-?(?P=char).*$', uid):
        return False
    
    # Else
    return True

n = int(input().strip())
lines = [input().strip() for x in range(n)]

for line in lines:
    print('Valid' if valid_cc_number(line) else 'Invalid')

Valid


## 90. Validating Postal Codes

In [41]:
regex_integer_in_range = r"^[1-9]\d{5}$"	# Do not delete 'r'.
regex_alternating_repetitive_digit_pair = r"(.)(?=.\1)"	# Do not delete 'r'.


import re
P = input()

print (bool(re.match(regex_integer_in_range, P)) 
and len(re.findall(regex_alternating_repetitive_digit_pair, P)) < 2)

False


## 91. Matrix Script

In [52]:
import math
import os
import random
import re
import sys

first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0]) #rows

m = int(first_multiple_input[1]) #columns

matrix = []

for _ in range(n):
    matrix_item = input()
    matrix.append(matrix_item)

decoded_str = ""


for j in range(m):
    for i in range(n):
        decoded_str += matrix[i][j]

final_decoded_str = re.sub('(\w)([^\w]+)(\w)', '\g<1> \g<3>', decoded_str)
print(final_decoded_str)


This is Matrix#  %!
